# Welcome to class


## Basics of Python:


In [4]:
L=[10,2.3,'Hello',[12,13]]
L

[10, 2.3, 'Hello', [12, 13]]

In [5]:
s="Welcome to python"
s

'Welcome to python'

In [6]:
t=(10,)#tuple with single
type(t)

tuple

In [8]:
t1=('Hi',)
type(t1)

tuple

In [9]:
s1={10,'Hi'}#Mutable set
s1

{10, 'Hi'}

In [10]:
type(s1)

set

In [11]:
s2={[10,20]}#We can not store mutable type data within set
s2

TypeError: unhashable type: 'list'

In [14]:
f=frozenset({10,'Hi'})
f

frozenset({10, 'Hi'})

In [13]:
#d={key:value}
d={'id':10,'name':'rob','age':23}
d

{'id': 10, 'name': 'rob', 'age': 23}

## Iterations in Python
* for loop
* while loop

In [15]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [17]:
for i in d:
    print(i)
    print(d[i])

id
10
name
rob
age
23


In [1]:
age=int(input("Enter age: "))
while age>18:
    print("You can vote in the election")
    break

Enter age: 19
You can vote in the election


In [2]:
def demo(a):
    return a
c=demo(19)

In [3]:
c

19

In [4]:
def demo(a):
    print(a)
c=demo(19)

19


In [5]:
c

## List comprehension

In [6]:
#Given range(1,51)
L=["FizzBuzz" if num%3==0 and num%5==0 else "Fizz" if num%3==0 else "Buzz" if num%5==0 else num for num in range(1,51)]
L

[1,
 2,
 'Fizz',
 4,
 'Buzz',
 'Fizz',
 7,
 8,
 'Fizz',
 'Buzz',
 11,
 'Fizz',
 13,
 14,
 'FizzBuzz',
 16,
 17,
 'Fizz',
 19,
 'Buzz',
 'Fizz',
 22,
 23,
 'Fizz',
 'Buzz',
 26,
 'Fizz',
 28,
 29,
 'FizzBuzz',
 31,
 32,
 'Fizz',
 34,
 'Buzz',
 'Fizz',
 37,
 38,
 'Fizz',
 'Buzz',
 41,
 'Fizz',
 43,
 44,
 'FizzBuzz',
 46,
 47,
 'Fizz',
 49,
 'Buzz']

## Anonymous Functions
## Lambda function
> Functions without name
syntax:

**lambda args:expression condition**

In [8]:
obj=lambda a,b:a+b if b>a else a-b
type(obj)

function

In [9]:
obj(5,6)

11

In [10]:
obj(15,6)

9

In [11]:
obj2=lambda num:"FizzBuzz" if num%3==0 and num%5==0 else "Fizz" if num%3==0 else "Buzz" if num%5==0 else num
obj2(15)

'FizzBuzz'

In [12]:
obj2(5)

'Buzz'

In [13]:
obj2(18)

'Fizz'

In [15]:
obj2(19)

19

### Using file object 
syntax:
  >file_obj=open(filename,mode="r")

### Using ```with``` keyword

syntax:
> with open(filename,mode="r") as label:
        label.operations

In [17]:
fobj=open('i2it_file demo.txt','a+')


In [19]:
for i in range(1,21):
    fobj.write(f"The square of {i} is {i*i}\n")
    fobj.flush()

In [20]:
fobj.seek(0)
line=fobj.readlines()#return list of lines
for i in line:
    print(i)

The square of 1 is 1

The square of 2 is 4

The square of 3 is 9

The square of 4 is 16

The square of 5 is 25

The square of 6 is 36

The square of 7 is 49

The square of 8 is 64

The square of 9 is 81

The square of 10 is 100

The square of 11 is 121

The square of 12 is 144

The square of 13 is 169

The square of 14 is 196

The square of 15 is 225

The square of 16 is 256

The square of 17 is 289

The square of 18 is 324

The square of 19 is 361

The square of 20 is 400

The square of 1 is 1

The square of 2 is 4

The square of 3 is 9

The square of 4 is 16

The square of 5 is 25

The square of 6 is 36

The square of 7 is 49

The square of 8 is 64

The square of 9 is 81

The square of 10 is 100

The square of 11 is 121

The square of 12 is 144

The square of 13 is 169

The square of 14 is 196

The square of 15 is 225

The square of 16 is 256

The square of 17 is 289

The square of 18 is 324

The square of 19 is 361

The square of 20 is 400



In [21]:
import sqlite3
con=sqlite3.connect("I2It_db_demo.db")


In [22]:
c=con.cursor()


In [23]:
c.execute("create table student (Sid int,Name text, Age int,Marks real)")

In [24]:
c.execute("insert into student (Sid,Name, Age, Marks) values (101,'Vinod',21,98.89)")
con.commit()

In [25]:
c.execute("update student set Marks=89.98 where Sid=101")
con.commit()

In [26]:
c.execute("select * from student")
print(c.fetchall())

[(101, 'Vinod', 21, 89.98)]


In [29]:
c.execute("delete from student where Sid=101")
con.commit()

In [32]:
class CollegeMem:
    def __init__(self,id,name,age):
        self.id=id
        self.name=name
        self.age=age
    def display(self):
        print(f"College Id: {self.id},\nName:{self.name}\nAge:{self.age}")
        
class Teacher(CollegeMem):
    def __init__(self,id,name,age,subject, salary):
        CollegeMem.__init__(self,id,name,age)
        self.sub=subject
        self.sal=salary
    def display(self):
        #CollegeMem.display(self)
        super().display()
        print(f"Subject: {self.sub},\nSalary: {self.sal}")
        
tobj=Teacher(10121,'Vidya',34,"Python",55888)
tobj.display()

College Id: 10121,
Name:Vidya
Age:34
Subject: Python,
Salary: 55888


# Regular Expression
> It is used to extract information from the text/db/csv



In [36]:
import re
fobj=open("i2it_file demo.txt")
lines=fobj.readlines()
d=[]
for l in lines[:20]:
    f=re.findall(r'[0-9]+',l)
    d.extend(f)
d

['1',
 '1',
 '2',
 '4',
 '3',
 '9',
 '4',
 '16',
 '5',
 '25',
 '6',
 '36',
 '7',
 '49',
 '8',
 '64',
 '9',
 '81',
 '10',
 '100',
 '11',
 '121',
 '12',
 '144',
 '13',
 '169',
 '14',
 '196',
 '15',
 '225',
 '16',
 '256',
 '17',
 '289',
 '18',
 '324',
 '19',
 '361',
 '20',
 '400']

In [136]:
import numpy as np

In [137]:
L1=[10,20,30,40]
L2=[50,60,70,80]


In [138]:
a1=np.array(L1)
a2=np.array(L2)

In [139]:
L1,L2,a1,a2

([10, 20, 30, 40],
 [50, 60, 70, 80],
 array([10, 20, 30, 40]),
 array([50, 60, 70, 80]))

In [140]:
#+ on list
L1+L2#concats 2 lists

[10, 20, 30, 40, 50, 60, 70, 80]

In [141]:
L1+100# TypeError

TypeError: can only concatenate list (not "int") to list

In [142]:
a1+a2#Adds respective elts

array([ 60,  80, 100, 120])

In [143]:
a1+100

array([110, 120, 130, 140])

#### * operator

In [144]:
L1*L2#Error

TypeError: can't multiply sequence by non-int of type 'list'

In [145]:
L1*2#Replicates list elts 2 times

[10, 20, 30, 40, 10, 20, 30, 40]

In [146]:
a1*a2#Multiplies to resp elts

array([ 500, 1200, 2100, 3200])

In [147]:
a1*2#Multiplies with 2 to each elts

array([20, 40, 60, 80])

In [148]:
a1**2

array([ 100,  400,  900, 1600], dtype=int32)

In [149]:
a2/a1

array([5.        , 3.        , 2.33333333, 2.        ])

In [150]:
np.zeros((3,3),dtype='int64')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [151]:
np.ones((3,3),dtype='int64')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [152]:
np.full((5,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [153]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [154]:
np.linspace(1,10,30)

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [155]:
for i in range(1,11,3.5):
    print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [156]:
np.arange(1.5,11.8,.5)

array([ 1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,
        7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5])

In [157]:
a2=np.random.rand(3,3)#values ranging from 0-1
a2

array([[0.17361015, 0.29139276, 0.12227086],
       [0.08567886, 0.88394075, 0.70493165],
       [0.51233496, 0.92404576, 0.10938731]])

In [158]:
a3=np.random.randn(3,3)#values 
a3

array([[-0.51003546, -0.69848577,  1.06475312],
       [-0.52732715,  1.02429457,  1.31012523],
       [ 0.08330241, -2.37223159, -1.57096844]])

In [159]:
a4=np.random.randint(1,11,size=(3,3))
a4

array([[10,  7,  2],
       [ 3, 10,  2],
       [ 7,  6,  5]])

In [160]:
a5=np.random.randint(11,111,size=(1000,10))
a5

array([[ 85,  50,  23, ...,  60,  91, 103],
       [ 73,  41, 108, ...,  20,  55,  44],
       [ 17,  83,  48, ...,  87, 106, 105],
       ...,
       [ 67,  14, 108, ...,  70,  27,  41],
       [ 69,  21,  22, ...,  38,  95,  87],
       [ 11,  58,  21, ..., 109,  98,  60]])

In [161]:
a5.min()

11

In [162]:
a5.max()

110

In [163]:
a5.mean()

60.3765

In [164]:
dir(a5)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [165]:
a5.view('float32')

array([[1.19e-43, 7.01e-44, 3.22e-44, ..., 8.41e-44, 1.28e-43, 1.44e-43],
       [1.02e-43, 5.75e-44, 1.51e-43, ..., 2.80e-44, 7.71e-44, 6.17e-44],
       [2.38e-44, 1.16e-43, 6.73e-44, ..., 1.22e-43, 1.49e-43, 1.47e-43],
       ...,
       [9.39e-44, 1.96e-44, 1.51e-43, ..., 9.81e-44, 3.78e-44, 5.75e-44],
       [9.67e-44, 2.94e-44, 3.08e-44, ..., 5.32e-44, 1.33e-43, 1.22e-43],
       [1.54e-44, 8.13e-44, 2.94e-44, ..., 1.53e-43, 1.37e-43, 8.41e-44]],
      dtype=float32)

In [166]:
a5.size#row x col

10000

In [167]:
a5.shape

(1000, 10)

In [168]:
a5.dtype

dtype('int32')

In [169]:
a5.ndim

2

In [170]:
a4

array([[10,  7,  2],
       [ 3, 10,  2],
       [ 7,  6,  5]])

In [171]:
a4.astype("float64")

array([[10.,  7.,  2.],
       [ 3., 10.,  2.],
       [ 7.,  6.,  5.]])

In [172]:
a4

array([[10,  7,  2],
       [ 3, 10,  2],
       [ 7,  6,  5]])

In [173]:
np.info(a4)

class:  ndarray
shape:  (3, 3)
strides:  (12, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x289690644c0
byteorder:  little
byteswap:  False
type: int32


In [174]:
a4

array([[10,  7,  2],
       [ 3, 10,  2],
       [ 7,  6,  5]])

In [175]:
a4.sort()

In [176]:
a4

array([[ 2,  7, 10],
       [ 2,  3, 10],
       [ 5,  6,  7]])

In [177]:
a4.sort(axis=0)#axis=0 col wise sorting 

In [178]:
a4

array([[ 2,  3,  7],
       [ 2,  6, 10],
       [ 5,  7, 10]])

In [179]:
a4.T

array([[ 2,  2,  5],
       [ 3,  6,  7],
       [ 7, 10, 10]])

In [180]:
a4

array([[ 2,  3,  7],
       [ 2,  6, 10],
       [ 5,  7, 10]])

In [181]:
a6=np.random.randint(1,11,size=(5,4))
a6

array([[ 6,  5,  2,  2],
       [ 3,  2,  3,  7],
       [ 6,  9,  4,  7],
       [ 7,  7,  3, 10],
       [ 8,  5,  4, 10]])

In [182]:
a6.size

20

In [183]:
a6.reshape((4,5))

array([[ 6,  5,  2,  2,  3],
       [ 2,  3,  7,  6,  9],
       [ 4,  7,  7,  7,  3],
       [10,  8,  5,  4, 10]])

In [184]:
a6.reshape((5,5))

ValueError: cannot reshape array of size 20 into shape (5,5)

In [185]:
a6.resize((5,5),refcheck=False)

In [186]:
a6

array([[ 6,  5,  2,  2,  3],
       [ 2,  3,  7,  6,  9],
       [ 4,  7,  7,  7,  3],
       [10,  8,  5,  4, 10],
       [ 0,  0,  0,  0,  0]])

In [187]:
a6[4]

array([0, 0, 0, 0, 0])

In [188]:
a6[4]=[4,5,6,7,8]

In [189]:
a6

array([[ 6,  5,  2,  2,  3],
       [ 2,  3,  7,  6,  9],
       [ 4,  7,  7,  7,  3],
       [10,  8,  5,  4, 10],
       [ 4,  5,  6,  7,  8]])

In [190]:
a2

array([[0.17361015, 0.29139276, 0.12227086],
       [0.08567886, 0.88394075, 0.70493165],
       [0.51233496, 0.92404576, 0.10938731]])

In [191]:
a3

array([[-0.51003546, -0.69848577,  1.06475312],
       [-0.52732715,  1.02429457,  1.31012523],
       [ 0.08330241, -2.37223159, -1.57096844]])

In [192]:
a2+a3

array([[-0.33642531, -0.40709301,  1.18702398],
       [-0.44164829,  1.90823532,  2.01505687],
       [ 0.59563737, -1.44818584, -1.46158113]])

In [193]:
np.split(a3,3)

[array([[-0.51003546, -0.69848577,  1.06475312]]),
 array([[-0.52732715,  1.02429457,  1.31012523]]),
 array([[ 0.08330241, -2.37223159, -1.57096844]])]

In [194]:
np.split(a3,3)

[array([[-0.51003546, -0.69848577,  1.06475312]]),
 array([[-0.52732715,  1.02429457,  1.31012523]]),
 array([[ 0.08330241, -2.37223159, -1.57096844]])]

In [195]:
a1

array([10, 20, 30, 40])

In [196]:
np.split(a1,1)

[array([10, 20, 30, 40])]

In [197]:
a5.shape

(1000, 10)

In [198]:
np.savetxt('I2it_numpy_file.txt',a5,delimiter=' ')

In [199]:
nobj=np.loadtxt('I2it_numpy_file.txt',delimiter=' ')
nobj

array([[ 85.,  50.,  23., ...,  60.,  91., 103.],
       [ 73.,  41., 108., ...,  20.,  55.,  44.],
       [ 17.,  83.,  48., ...,  87., 106., 105.],
       ...,
       [ 67.,  14., 108., ...,  70.,  27.,  41.],
       [ 69.,  21.,  22., ...,  38.,  95.,  87.],
       [ 11.,  58.,  21., ..., 109.,  98.,  60.]])

In [200]:
a6

array([[ 6,  5,  2,  2,  3],
       [ 2,  3,  7,  6,  9],
       [ 4,  7,  7,  7,  3],
       [10,  8,  5,  4, 10],
       [ 4,  5,  6,  7,  8]])

In [201]:
a6[0]

array([6, 5, 2, 2, 3])

In [202]:
a6[:3]

array([[6, 5, 2, 2, 3],
       [2, 3, 7, 6, 9],
       [4, 7, 7, 7, 3]])

In [203]:
a6[1:4,1:4]

array([[3, 7, 6],
       [7, 7, 7],
       [8, 5, 4]])

In [204]:
#first 4 rows and 4 cols data:
a6[:4,:4]

array([[ 6,  5,  2,  2],
       [ 2,  3,  7,  6],
       [ 4,  7,  7,  7],
       [10,  8,  5,  4]])

In [205]:
a6[-3:,-3:]

array([[ 7,  7,  3],
       [ 5,  4, 10],
       [ 6,  7,  8]])

In [207]:
import pickle
data2 =  {'a': 5, 'b': 10, 'c': 20}
b=pickle.dumps(data2)
b

b'\x80\x03}q\x00(X\x01\x00\x00\x00aq\x01K\x05X\x01\x00\x00\x00bq\x02K\nX\x01\x00\x00\x00cq\x03K\x14u.'